// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for OrderStatus.
const (
	Created OrderStatus = "created"
	Paid    OrderStatus = "paid"
)

// Order defines model for Order.
type Order struct {
	// Id The unique identifier of the order
	ID int `json:"id"`

	// PaymentKey The payment key of the order
	PaymentKey string `json:"payment_key"`

	// Status The status of the order
	Status OrderStatus `json:"status"`

	// TotalPrice The total price of the order
	TotalPrice float32 `json:"total_price"`
}

// OrderStatus The status of the order
type OrderStatus string

// PostOrder defines model for PostOrder.
type PostOrder struct {
	// Products The products of the order
	Products []struct {
		// Id The unique identifier of the product
		ID int `json:"id"`

		// Image The image of the product
		Image string `json:"image"`

		// Name The name of the product
		Name string `json:"name"`

		// Price The price of the product
		Price    float32 `json:"price"`
		Quantity int     `json:"quantity"`
	} `json:"products"`
}

// StripeEvent defines model for StripeEvent.
type StripeEvent struct {
	ApiVersion openapi_types.Date `json:"api_version"`
	Created    int                `json:"created"`
	Data       *struct {
		Object *StripeObject `json:"object,omitempty"`
	} `json:"data,omitempty"`
	ID     string `json:"id"`
	Object string `json:"object"`
	Type   string `json:"type"`
}

// StripeObject defines model for StripeObject.
type StripeObject struct {
	Id            string  `json:"id"`
	Object        string  `json:"object"`
	PaymentIntent *string `json:"payment_intent,omitempty"`
	PaymentStatus *string `json:"payment_status,omitempty"`
	Status        string  `json:"status"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = PostOrder

// ProcessStripeEventJSONRequestBody defines body for ProcessStripeEvent for application/json ContentType.
type ProcessStripeEventJSONRequestBody = StripeEvent
