version: "3.9"

networks:
  training-store-backend:
    driver: bridge

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - training-store-backend

  training-store:
    image: training-store-backend:latest
    container_name: training-store
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - training-store-backend
    volumes:
      - ./web/stripe:/app/web/stripe
      - ./storage:/app/storage


  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.21
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - training-store-backend